services:
  notebook:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ~/.ssh:/home/jovyan/.ssh
      - ~/code/py/ipynb:/home/jovyan/work:rw
      - ~/Downloads:/Downloads:rw
      - ~/Documents:/Documents:rw
      - ~/git:/git:rw
