[project]
name = "pixi_jupyter_container"
version = "1.0.0"
channels = ["conda-forge"]
platforms = ["linux-aarch64"]

[dependencies]
python = "*"
jupyterlab = "*"
numpy = "*"
pandas = "*"
scikit-learn = "*"
scipy = "*"
seaborn = "*"
statsmodels = "*"
beautifulsoup4 = "*"
ffmpeg-python = "*"
html5lib = "*"
lxml = "*"
lz4 = "*"
nltk = "*"
opencv = "*"
requests = "*"
jupyterlab_execute_time = "*"
ipyflow = "*"

[pypi-dependencies]
polyleven = "*"
uncurl = "*"
jupyterlab-skip-traceback = "*"
